Enables the prescription of a distribution mean from a previous HM
equinor/flownet pull request #127
Opened 2020-08-21 08:52 UTC by olwijn

Closes #66 

The functionality is activated by adding the keyword ahm_case to the model_parameters section of the config:

![image](https://user-images.githubusercontent.com/13539085/90872010-41689e00-e39c-11ea-8c15-b7a00fe98b89.png)

The specified folder is currently expected to contain the file parameters_iteration-latest.parquet.gzip

2020-08-27 07:21 UTC, olwijn commented on src/flownet/ahm/_run_ahm.py
> +            if loguniform is True:
I have now created a separate function to determine min/max

2020-08-27 07:21 UTC, olwijn commented on src/flownet/ahm/_run_ahm.py
> +def update_distribution(parameters, ahm_case):
type annotation was added

2020-08-28 14:51 UTC, olwijn commented
![image](https://user-images.githubusercontent.com/13539085/91581318-984b1600-e94e-11ea-9981-b967fabdcc5b.png)

I don't quite understand the problem. reveal_type(parameters) on input and output gives:

![image](https://user-images.githubusercontent.com/13539085/91581467-c03a7980-e94e-11ea-8299-737e64b18aa7.png)

2020-09-03 09:38 UTC, wouterjdb commented
Mypy is complaining about that you tried to get attributes from something which is allowed to be a str, according to the input type,

`parameters: Union[str, List[str]]`

and a string does not have these attributes.

2020-09-11 13:09 UTC, olwijn commented
Two more changes are needed to fully integrate this functionality: (1) add a test to workflow.yml in .github/workflows : add a second history match run with restart after the first one and before the prediction run, (2) do not rebuild the flownet when using the restart, but instead use the functionality used for prediction runs to read in the flownet.

2020-09-11 13:54 UTC, olwijn commented
Two more changes are needed to fully integrate this functionality: (1) add a test to workflow.yml in .github/workflows : add a second history match run with restart after the first one and before the prediction run, (2) do not rebuild the flownet when using the restart, but instead use the functionality used for prediction runs to read in the flownet.

2020-09-17 19:55 UTC, anders-kiaer commented on .github/workflows/flownet.yml
>            flownet ahm ./config/assisted_history_matching.yml ./some_ahm_run --update-config ./ci_config/assisted_history_matching.yml
Can we add one line here where the new functionality is used? Then we are sure the added functionality runs :green_heart: :slightly_smiling_face:

2020-09-18 16:26 UTC, wouterjdb requested changes
LGTM - two minor things. You can change those from within your browser (accept the suggestions). Approved afterward. 👍

2020-09-18 16:26 UTC, wouterjdb commented on src/flownet/_command_line.py
> +        "Any relative paths in this file will also be assumed relative to the main config.",
```suggestion
        help="Optional folder containing results from a previous history match.",
```

2020-09-18 16:26 UTC, wouterjdb commented on src/flownet/ahm/_assisted_history_matching.py
> +        Returns:self.output_folder
```suggestion
        Returns:
```

2020-09-21 12:51 UTC, anders-kiaer reviewed
One minor suggestion, otherwise LGTM as well.

2020-09-21 12:51 UTC, anders-kiaer commented on src/flownet/ahm/_run_ahm.py
```suggestion

```

2020-09-21 12:52 UTC, wouterjdb approved these changes

2020-09-23 07:02 UTC, merged