Observation vectors in config yaml
equinor/flownet pull request #147
Opened 2020-08-27 09:39 UTC by olelod

Testing potential implications of removing WGPR from Egg ci_config YAML on testdata repository

2020-08-28 13:33 UTC, olelod commented
Closes #145 and #153

2020-09-03 09:26 UTC, wouterjdb requested changes

2020-09-03 09:26 UTC, wouterjdb commented on src/flownet/templates/observations.ertobs.jinja2
> +SUMMARY_OBSERVATION WWIR_{{ kw.well_name }}_{{ index_name }} { VALUE = {{ kw.rate }}; ERROR = {{ [error_config.WWIR.rel_error * kw.rate, error_config.WWIR.min_error] | max }}; DATE = {{ date_formatte
```suggestion
SUMMARY_OBSERVATION WWIR_{{ kw.well_name }}_{{ index_name }} { VALUE = {{ kw.rate }}; ERROR = {{ [error_config.WWIR.rel_error * kw.rate, error_config.WWIR.min_error] | max }}; DATE = {{ date_formatted  }}; KEY = WWIR:{{ kw.well_name }}; };
```

2020-09-03 11:34 UTC, wouterjdb requested changes

2020-09-03 11:34 UTC, wouterjdb commented on src/flownet/templates/observations.yamlobs.jinja2
> +      error: {{ [error_config.WTHP.rel_error * kw.bhp, error_config.WTHP.min_error] | max }}
This should be THP I guess?

```suggestion
      error: {{ [error_config.WTHP.rel_error * kw.thp, error_config.WTHP.min_error] | max }}
```

2020-09-03 12:17 UTC, wouterjdb approved these changes
LGTM 🚀

2020-09-03 12:25 UTC, merged