I139 eqlnum satnum regions
equinor/flownet pull request #160
Opened 2020-09-01 11:28 UTC by olelod

*Insert a description of your pull request (PR) here, and check off the boxes below when they are done.*

---

### Contributor checklist

- [ ] :tada: This PR closes #139.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Assign eqlnum/satnum regions from simulation to FlowNet model
   - [ ] Testing
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`.
- [ ] :books: I have considered updating the documentation.

2020-09-09 07:36 UTC, wouterjdb requested changes

2020-09-09 07:36 UTC, wouterjdb commented on src/flownet/ahm/_run_ahm.py
> +    z_mid = network.grid[["z0", "z1", "z2", "z3", "z4", "z5", "z6", "z7"]].mean(axis=1)
Maybe make a property out of this.

You can copy that from my PR:

https://github.com/equinor/flownet/pull/155/files

2020-09-14 10:06 UTC, wouterjdb requested changes

2020-09-14 10:06 UTC, wouterjdb commented on src/flownet/data/from_flow.py
> +    def get_unique_regions(self, name) -> np.ndarray:
```suggestion
    def get_unique_regions(self, name: str) -> np.ndarray:
```

2020-09-14 10:09 UTC, olelod commented on src/flownet/ahm/_run_ahm.py
> +        The function loops through each cell in all flow tubes, and checks what 'name' region the
Name is an input: EQLNUM or SATNUM

2020-09-14 11:09 UTC, olelod commented on src/flownet/ahm/_run_ahm.py
> +        The function loops through each cell in all flow tubes, and checks what 'name' region the
Slightly rewritten in new commit

2020-09-14 15:14 UTC, wouterjdb approved these changes
LGTM 🚀

2020-09-14 15:21 UTC, merged