layers added to input yaml and parsed by the config parser
equinor/flownet pull request #279
Opened 2020-12-03 15:18 UTC by LonnekevB

*Insert a description of your pull request (PR) here, and check off the boxes below when they are done.*

---

### Contributor checklist

- [ ] :tada: This PR closes #ISSUE_NUMBER.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Task 1
   - [ ] Task 2
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`.
- [ ] :books: I have considered updating the documentation.

2020-12-18 09:01 UTC, LonnekevB commented
New issue has been made on adapting the perforation strategy methods to layering. Not sure whether to make unit tests for the well_connections function within this pull request or within the new pull request on layering in perforation strategy (as these methods are kind of incorporated in the well_connections method).

2020-12-18 19:36 UTC, wouterjdb requested changes
> New issue has been made on adapting the perforation strategy methods to layering. 

Good. For reference: #290 

> Not sure whether to make unit tests for the well_connections function within this pull request or within the new pull request on layering in perforation strategy (as these methods are kind of incorporated in the well_connections method).

You can do that in the new PR.

This looks very good, some minor comments and we're ready to go 👍

2020-12-18 19:36 UTC, wouterjdb commented on src/flownet/data/from_flow.py
> +                f"Number of layers from config ({self._layers[-1][-1]}) is not equel to "
```suggestion
                f"Number of layers from config ({self._layers[-1][-1]}) is not equal to "
```

2021-01-06 12:02 UTC, LonnekevB reviewed
All changes are made

2021-01-06 13:00 UTC, wouterjdb approved these changes
LGTM 👍

2021-01-06 13:02 UTC, merged