Add brine p
equinor/flownet pull request #417
Opened 2021-06-18 10:11 UTC by plgbrts

This PR continues PR #410 (add brine support)

This PR  adds on top of P#410  the creation of WSALT entries in the HISTORY_SCHEDULE.inc

The  flownet-testcases/ norne_salt  (PR #50 of flownet-testcases repo) is used as testcase
---

### Contributor checklist

- [ x] : This PR closes #381.
- [ x]  I have broken down my PR into the following tasks:
   - [x] The creation of WSALT entries in the  HISTORY_SCHEDULE.in
- [ x] : I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
          - flownet-testcases/ norne_salt 
- [ ]  I have considered adding a new entry in `CHANGELOG.md`.
- [ ]  I have considered updating the documentation.

2021-06-25 09:57 UTC, olelod commented on src/flownet/config_parser/_config_parser.py
> +                                            "WSPR": {
The other vectors have both rate and cumulative. Does it make sense to add WSPT here as well?

2021-06-25 09:58 UTC, olelod commented on src/flownet/data/from_flow.py
> +                - WSPR          Well Salt Production Rate
Same here. WSPT, WSIT?

2021-06-25 09:59 UTC, olelod commented on src/flownet/data/from_flow.py
> +            "WSPR",
And here. WSPT, WSIT?

2021-06-25 10:05 UTC, olelod commented on src/flownet/realization/_schedule.py
> +                        salt_rate=value["WSPR"],
i guess we are only interested in salt_rate? could add salt_total here as well.

2021-06-25 10:07 UTC, olelod commented on src/flownet/realization/_simulation_keywords.py
> +        salt_rate: float = np.nan,
salt_total?

2021-06-25 10:07 UTC, olelod commented on src/flownet/realization/_simulation_keywords.py
> +        self.salt_rate: float = salt_rate
salt_total?

2021-06-25 10:08 UTC, olelod commented on src/flownet/static/SUMMARY.inc
> +WSPR
WSPT, WSIT?

2021-06-25 10:10 UTC, olelod commented on src/flownet/templates/observations.ertobs.jinja2
> +{%- if not isnan(kw.salt_rate) and error_config.WSPR.rel_error is not none and error_config.WSPR.min_error is not none: %}
could also add possibility for salt_total / WSPT here for completeness, but i guess none will ever use it...

2021-06-25 10:11 UTC, olelod commented on src/flownet/templates/observations.yamlobs.jinja2
> +   {%- if (error_config.WSPR.rel_error is not none) and (error_config.WSPR.min_error is not none) -%}
same here with WSPT

2021-06-25 10:11 UTC, olelod commented on tests/test_check_obsfiles_ert_yaml.py
> +    config.flownet.data_source.simulation.vectors.WSPR = collections.namedtuple(
if we add WSPT it needs to go in here as well

2021-06-25 10:17 UTC, olelod requested changes
You should add an item to the CHANGELOG stating that FlowNet now supports brine simulation.

Other that that it looks nice!

I commented all the places where a potential cumulative vector for salt could be added. I don't know enough about brine simulations to know if it is ever used by someone, but I see the vectors are available in OPM Flow, at least. If it is something that is not used at all we should not add them.

2021-06-25 16:30 UTC, plgbrts commented
> You should add an item to the CHANGELOG stating that FlowNet now supports brine simulation.
> 
> Other that that it looks nice!
> 
> I commented all the places where a potential cumulative vector for salt could be added. I don't know enough about brine simulations to know if it is ever used by someone, but I see the vectors are available in OPM Flow, at least. If it is something that is not used at all we should not add them.

I followed your suggestions to generalise and to allow also for WSPT, WSIT, WSIR, similarly as done e.g. for water production/injection (WWXX).

2021-06-28 11:19 UTC, olelod commented on src/flownet/templates/observations.ertobs.jinja2
> +{%- if not isnan(kw.salt_rate) and error_config.WSIR.rel_error is not none and error_config.WSIR.min_error is not none: %}
I think WSIR should not be under WCONHIST, only under WCONINJ, so these lines can be removed.

2021-06-28 11:22 UTC, olelod requested changes
Just one small thing in the observations.ertobs.jinja2 template and we should be good to go!

2021-06-28 12:54 UTC, plgbrts commented
Many thanks for all the good suggestions. I removed the WSIR from WCONHIST.

2021-06-28 13:54 UTC, olelod approved these changes

2021-06-29 06:53 UTC, merged