adaptations to allow for production temperature history matching
equinor/flownet pull request #443
Opened 2021-10-30 13:32 UTC by plgbrts

The purpose of this PR is to allow for history matching production fluid temperatures. Main adjustement:
1) keyword `WTPCHEA` (temperature of producers) added for parsing  (`_config_parser.py`)
2) extended `phases` with additional element `temp`. Also `brine` is allowed now to be specified under `phases` item in the yml config file. Thus the items `'oil', 'gas', 'water', 'disgas', 'vapoil', 'brine' and 'temp'` can all be specified now under the `phases` keyword. (Note the term `phases ` is not so appropriate anymore and should may be renamed) (`_config_parser.py`)
3) added `WTPCHEA` and `WTICHEA` to dataframe (`from_flow.py`)
4) helper function adedd to create `WTEMP` for injection temperature specification. The `has_brine` method commented out as `brine` keyword should now be specified via `phases` keyword in the config yml file (`_schedule.py`)
5) further adjustments to template files to enable `WTEMP` writing to schedule include file and to allow for production temperature observations

todo: 
1) Enable specifying grid property THCONR ( total thermal conductivity) as static property for a flownet simulation. See issue #442 
2) add a brine +thermal test case to flownet-testdata repository
3) update documentation and changelog

2021-11-01 08:27 UTC, fahaddilib approved these changes
Great work Paul. Let's get this merged in.

2021-11-01 08:28 UTC, fahaddilib requested changes
Great work Paul. Lets get this merged in. But there is some problems with the formatting which is failing to the tests.

2021-11-01 08:29 UTC, olelod commented
Nice job! There is a few formatting issues, I see. I'll fix them and merge later today.

2021-11-01 10:29 UTC, olelod approved these changes
LGTM

2021-11-03 09:07 UTC, plgbrts commented
Thanks Ole Petter for fixing the format issues! I see that merging is blocked because of the requested change of @fahaddilib but that is resolved by @olelod. Let me know if there is still something to be done on my side.

2021-11-05 08:35 UTC, fahaddilib approved these changes

2021-11-05 12:13 UTC, merged